import json # reads transcript.json
from ollama import chat # sends a prompt to Qwen through Ollama

with open("output/transcript.json", "r", encoding="utf-8") as file:
    # load the JSON file
    transcript = json.load(file)

    # ask user for video description
    video_description = input(
        "Describe the video and what kind of content it is: "
    )

    print("Transcript segments:", len(transcript))

    transcript_text = ""

    # compile the transcript text from the JSON
    for segment in transcript:
        line = (
            f"{segment['start']} -> {segment['end']}\n"
            f"Text: {segment['text']}\n"
            f"Reliability: {segment['reliability']}\n"
        )

        transcript_text += line


# construct prompt
prompt = f"""
You are analyzing a video transcript to find interesting moments.

VIDEO CONTEXT:
{video_description}

Use the video context to help understand the meaning and tone
of the transcript.

Find moments belonging to these categories:

- funny
- surprising
- positive

For each moment, return:

- start: start timestamp
- end: end timestamp
- type: funny, surprising, or positive
- confidence: number from 0.0 to 1.0
- description: short explanation of why the moment was detected

IMPORTANT RULES:

1. Only use timestamps that exist in the transcript.

2. The transcript was automatically generated by Whisper
   and may contain transcription errors.

3. Be cautious with segments marked as low reliability.

4. Do not classify something as funny or surprising solely
   because a low-reliability transcription sounds strange.

5. A moment does not have to be detected. Do not force a
   category when there is not enough evidence.

6. Since you only have transcript information right now,
   be conservative about emotions that depend on tone of
   voice or facial expressions.

Return ONLY valid JSON in this format:

{{
    "moments": [
        {{
            "start": 12.4,
            "end": 16.8,
            "type": "funny",
            "confidence": 0.82,
            "description": "The speaker makes a joke about the failed test."
        }}
    ]
}}

If there are no interesting moments, return:

{{
    "moments": []
}}

TRANSCRIPT:

{transcript_text}
"""

print("Analyzing transcript...")

# ask ollama for json
response = chat(
    model="qwen3:8b",
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    format="json",
    think=False,
)

# get the raw response
raw_response = response.message.content


# convert qwen's response to python data
result = json.loads(
    raw_response
)

# print each detected moment
for moment in result["moments"]:
    print()
    print("Type:", moment["type"])
    print("Time:", moment["start"], "->", moment["end"])
    print("Confidence:", moment["confidence"])
    print("Why:", moment["description"])

# save the results
with open(
    "output/moments.json",
    "w",
    encoding="utf-8",
) as file:
    json.dump(
        result,
        file,
        indent=2,
        ensure_ascii=False,
    )





